### ISSUE TITLE
Octomap: octomap not cleared between flights

### ISSUE THREAD

**Issue by jnippula** [tiiuae/fog_sw#74]
If obstacles are moved of drone is hand carried between missions the old octomap gives incorrect information and drone may start inside no-go zone or tries to avoid nonexistent obstacles.
Would be good to have configuration to choose whether octomap is:
1) cleared automatically in every arming/takeoff 
or 
2) kept untouched and reset only by manual service call

**Comment by spurnvoj** [comment]
This feature is included in this PR https://github.com/tiiuae/control_interface/pull/9

**Comment by jnippula** [comment]
Merged

**Comment by jnippula** [comment]
Verified
